# ---- Build Stage ----
FROM eclipse-temurin:17 AS build

# Set working directory inside the build container
WORKDIR /app

# Copy only the necessary files to leverage Docker caching
COPY ./gradlew gradlew
COPY gradle gradle
COPY build.gradle ./
COPY src ./src

RUN chmod +x gradlew


# Build the Spring Boot application
RUN ./gradlew clean build -x test

# ---- Run Stage ----
FROM eclipse-temurin:17

# Set working directory inside the final container
WORKDIR /app

# Copy the built JAR from the previous stage
COPY --from=build /app/build/libs/*.jar post-service.jar

# Expose the application port
EXPOSE 8083

# Run the Spring Boot application
ENTRYPOINT ["java", "-jar", "post-service.jar"]