# Use an official Python runtime as a parent image
FROM python:3.10-slim

# Set the working directory in the container
WORKDIR /app

# Copy the requirements.txt file into the container
COPY ./requirements.txt /app/requirements.txt

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir --upgrade -r /app/requirements.txt

# Copy the rest of your application code into the container
COPY ./app /app/app

# Expose the port that Uvicorn will run on
EXPOSE 8084

# Command to run the FastAPI application with Uvicorn
# Use the "exec" form for graceful shutdown and lifespan events
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8084"]