version: '3.7'
services:
  gateway-service:
    build:
      context: ./gateway-service
      dockerfile: ./dockerfile
    environment:
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - "8081:8081"
    volumes:
      - gateway-gradle-cache:/home/gradle/.gradle

  user-service:
    build:
      context: ./user-service
      dockerfile: ./dockerfile   # Use the Dockerfile to build the app
    environment:
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - user-gradle-cache:/home/gradle/.gradle
    depends_on:
      - db


  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    env_file:
      - .env
    ports:
      - "5433:5432"
volumes:
  gateway-gradle-cache:
  user-gradle-cache: