version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile   # Use the Dockerfile to build the app
    environment:
      - DB_URL=jdbc:postgresql://db:5432/mydb
      - DB_USERNAME=your_db_username
      - DB_PASSWORD=your_db_password
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: your_db_username
      POSTGRES_PASSWORD: your_db_password
    ports:
      - "5432:5432"