spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: user-service-login
          uri: http://user-service:8080/
          predicates:
            - Path=/users/login
            - Method=POST
          filter:
            - JwtFilter
        - id: user-service-signup
          uri: http://user-service:8080/
          predicates:
            - Path=/users/signup
            - Method=POST
          filter:
            - JwtFilter
jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000
server:
  port: 8081
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
management: # <-- Add this section if it doesn't exist
  endpoints:
    web:
      exposure:
        include: health,info,gateway # <-- Ensure 'gateway' is included here