spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8080
          predicates:
            - Path=/users/**
          filters:
            - RewritePath=/orders/(?<path>.*), /$\{path}
            - AddRequestHeader=X-User-Id, #{principal.userId} # ← inject from JWT claims
jwt:
  secret: yourverylongandsecurejwtsecretkeythatshouldbepersistent
  expiration: 3600000