spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: user-service-login
          uri: http://user-service:8080/
          predicates:
            - Path=/users/login
            - Method=POST
        - id: user-service-register
          uri: http://user-service:8080/
          predicates:
            - Path=/users/register/**
            - Method=POST
        - id: user-service-refresh
          uri: http://user-service:8080/
          predicates:
            - Path=/users/refresh
            - Method=POST
        - id: user-service-protected
          uri: http://user-service:8080/
          predicates:
            - Path=/users/**
          filters:
            - JwtHeader
        - id: verification-service-protected
          uri: http://verification-service:8082/
          predicates:
            - Path=/token/**
          filters:
            - JwtHeader
        - id: post-service-protected
          uri: http://post-service:8083/
          predicates:
            - Path=/posts/register/**
          filters:
            - JwtHeader
jwt:
  jwk-set-uri: ${JWK_SET_URI}
  issuer-uri: ${ISSUER_URI}
  expiration: 3600000
server:
  port: 8080
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
management: # <-- Add this section if it doesn't exist
  endpoints:
    web:
      exposure:
        include: health,info,gateway # <-- Ensure 'gateway' is included here