spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081/ # Used to be localhost:8080 but modified to 8081 during merge conflict resolution
          predicates:
            - Path=/users/login
            - Method=POST
          filters:
            - Authorization
        - id: user-service-signup
          uri: http://user-service:8080/
          predicates:
            - Path=/users/signup
            - Method=POST
          filters:
            - Authorization
jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000
server:
  port: 8080
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
management: # <-- Add this section if it doesn't exist
  endpoints:
    web:
      exposure:
        include: health,info,gateway # <-- Ensure 'gateway' is included here