package com.omniversity.server.user.entity;

public enum Program {
    // Engineering & Technology
    COMPUTER_SCIENCE,
    COMPUTER_ENGINEERING,
    DATA_SCIENCE,
    ELECTRICAL_ENGINEERING,
    SOFTWARE_ENGINEERING,
    MECHANICAL_ENGINEERING,
    CIVIL_ENGINEERING,
    AEROSPACE_ENGINEERING,
    CHEMICAL_ENGINEERING,
    BIOMEDICAL_ENGINEERING,
    INDUSTRIAL_ENGINEERING,
    MECHATRONICS,

    // NATURAL SCIENCE
    BIOLOGY,
    CHEMISTRY,
    PHYSICS,
    MATHEMATICS,
    ENVIRONMENTAL_SCIENCE,
    GEOLOGY,
    ASTRONOMY,
    MARINE_SCIENCE,

    // BUSINESS & ECONOMICS
    ACCOUNTING,
    FINANCE,
    MARKETING,
    MANAGEMENT,
    INTERNATIONAL_BUSINESS,
    SUPPLY_CHAIN_MANAGEMENT,
    HUMAN_RESOURCE_MANAGEMENT,
    ENTREPRENEURSHIP,
    ECONOMICS,

    // HEALTH & MEDICAL SCIENCE
    NURSING,
    PUBLIC_HEALTH,
    KINESIOLOGY,
    NUTRITION,
    HEALTH_SCIENCE,
    BIOMEDICAL_SCIENCE,

    // PROFESSIONAL DEGREE
    MEDICINE,
    LAW,
    DENTISTRY,

    // ARTS & HUMANITIES
    ENGLISH_LITERATURE,
    HISTORY,
    PHILOSOPHY,
    LINGUISTICS,
    ART_HISTORY,
    MUSIC,
    THEATRE,
    PERFORMANCE_ARTS,
    RELIGIOUS_STUDIES,
    CLASSICS,
    MODERN_LANGUAGES,

    // SOCIAL SCIENCE
    PSYCHOLOGY,
    SOCIOLOGY,
    POLITICAL_SCIENCE,
    ANTHROPOLOGY,
    INTERNATIONAL_RELATIONS,
    CRIMINOLOGY,

    // FINE ARTS & DESIGN
    VISUAL_ARTS,
    GRAPHIC_DESIGN,
    INDUSTRIAL_DESIGN,
    FASHION_DESIGN,
    PHOTOGRAPHY,
    ANIMATION,
    FILM_MEDIA_STUDIES,
    COMPUTER_GRAPHICS,

    // EDUCATION
    ELEMENTARY_EDUCATION,
    SECONDARY_EDUCATION,
    SPECIAL_EDUCATION,

    // OTHER FIELDS
    COMMUNICATION_STUDIES,
    JOURNALISM,
    MEDIA_STUDIES,
    URBAN_STUDIES,
    LIBERAL_ARTS,
    COGNITIVE_SCIENCE,
    STATISTICS,
    GEOGRAPHY



}
