CREATE TABLE IF NOT EXISTS "USER" (
    id INT NOT NULL,
    NAME VARCHAR(50) NOT NULL,
    PRIVATE_EMAIL VARCHAR(100) NOT NULL UNIQUE,
    PASSWORD_HASH VARCHAR(100) NOT NULL,
    USER_ID VARCHAR(50) NOT NULL UNIQUE,
    DATE_OF_BIRTH DATE NOT NULL,
    IS_ADMIN BIT,
    EXCHANGE_UNI VARCHAR(80),
    HOME_UNI VARCHAR(80),
    EXCHANGE_EMAIL VARCHAR(80) UNIQUE,
    HOME_EMAIL VARCHAR(80) UNIQUE,
    NATIONALITY VARCHAR(50),
    EXCHANGE_START DATE,
    EXCHANGE_END DATE,
    PREFERRED_LANGUAGE VARCHAR(50),
    IS_ACTIVE BIT
);