# Use OpenJDK 17 image as base
FROM openjdk:17-jdk-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the application jar (built by Gradle or Maven) into the container
COPY build/libs/user-service-0.0.1-SNAPSHOT.jar app.jar

# Expose the port your app runs on
EXPOSE 8080

# Command to run the Spring Boot app
CMD ["java", "-jar", "app.jar"]