# Docker Compose file to setup the database
# Currently defined to be set up as PSQL v17
version: '3.8'
services:
  dev-db:
    image: postgres:17
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRESS_DN: omniversity

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./user-service:/app
    depends_on:
      - dev-db